
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziXbtXt8_-rJ_ZlQU6WMSXJosmo5PWbU',
    appId: '1:651228881066:web:341e3d7351c07e9439b0d3',
    messagingSenderId: '651228881066',
    projectId: 't-store-1883f',
    authDomain: 't-store-1883f.firebaseapp.com',
    storageBucket: 't-store-1883f.firebasestorage.app',
    measurementId: 'G-K1ZF49CJ0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC-KV53eFQ4md5ieHPWe-VO2JNdRpJWS8',
    appId: '1:651228881066:android:651acdb14d32363939b0d3',
    messagingSenderId: '651228881066',
    projectId: 't-store-1883f',
    storageBucket: 't-store-1883f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9LgVzSqmb8OwK8mtHC47YIfkBxBdMYvE',
    appId: '1:651228881066:ios:69faa2714711e77739b0d3',
    messagingSenderId: '651228881066',
    projectId: 't-store-1883f',
    storageBucket: 't-store-1883f.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9LgVzSqmb8OwK8mtHC47YIfkBxBdMYvE',
    appId: '1:651228881066:ios:69faa2714711e77739b0d3',
    messagingSenderId: '651228881066',
    projectId: 't-store-1883f',
    storageBucket: 't-store-1883f.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDziXbtXt8_-rJ_ZlQU6WMSXJosmo5PWbU',
    appId: '1:651228881066:web:548139a7daf6cd9839b0d3',
    messagingSenderId: '651228881066',
    projectId: 't-store-1883f',
    authDomain: 't-store-1883f.firebaseapp.com',
    storageBucket: 't-store-1883f.firebasestorage.app',
    measurementId: 'G-FBYWB9RY87',
  );
}
